image: freebsd/latest
packages:
  - meson
  - pkgconf
  - hidapi
  - qt5-buildtools
  - qt5-dbus
  - qt5-testlib
sources:
  - https://git.sr.ht/~z3ntu/razer_test
tasks:
  - setup: |
      cd razer_test
      meson -Dbuild_bringup_util=true -Dbuild_tests=true builddir
  - build: |
      cd razer_test
      ninja -C builddir
  - test: |
      cd razer_test
      ninja -C builddir test
