/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp devicemanager.xml -a devicemanageradaptor.h:devicemanageradaptor.cpp -c DeviceManagerAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "devicemanageradaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class DeviceManagerAdaptor
 */

DeviceManagerAdaptor::DeviceManagerAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

DeviceManagerAdaptor::~DeviceManagerAdaptor()
{
    // destructor
}

QString DeviceManagerAdaptor::version() const
{
    // get the value of property version
    return qvariant_cast< QString >(parent()->property("version"));
}

QVector<QDBusObjectPath> DeviceManagerAdaptor::getDevices()
{
    // handle method call io.github.openrazer1.Manager.getDevices
    QVector<QDBusObjectPath> out0;
    QMetaObject::invokeMethod(parent(), "getDevices", Q_RETURN_ARG(QVector<QDBusObjectPath>, out0));
    return out0;
}

QString DeviceManagerAdaptor::getVersion()
{
    // handle method call io.github.openrazer1.Manager.getVersion
    QString out0;
    QMetaObject::invokeMethod(parent(), "getVersion", Q_RETURN_ARG(QString, out0));
    return out0;
}

