/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp razerdevice.xml -a razerdeviceadaptor.h:razerdeviceadaptor.cpp -c RazerDeviceAdaptor
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef RAZERDEVICEADAPTOR_H
#define RAZERDEVICEADAPTOR_H
#include "../device/razerdevice.h"
#include "../led/razerled.h"

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
QT_BEGIN_NAMESPACE
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;
QT_END_NAMESPACE

/*
 * Adaptor class for interface io.github.openrazer1.Device
 */
class RazerDeviceAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "io.github.openrazer1.Device")
    Q_CLASSINFO("D-Bus Introspection", ""
                "  <interface name=\"io.github.openrazer1.Device\">\n"
                "    <property access=\"read\" type=\"s\" name=\"Name\"/>\n"
                "    <property access=\"read\" type=\"s\" name=\"Type\"/>\n"
                "    <property access=\"read\" type=\"a(i)\" name=\"LedIds\">\n"
                "      <annotation value=\"QVector&lt;RazerLedId&gt;\" name=\"org.qtproject.QtDBus.QtTypeName\"/>\n"
                "    </property>\n"
                "    <property access=\"read\" type=\"as\" name=\"SupportedFx\"/>\n"
                "    <property access=\"read\" type=\"as\" name=\"SupportedFeatures\"/>\n"
                "    <method name=\"getSerial\">\n"
                "      <arg direction=\"out\" type=\"s\"/>\n"
                "    </method>\n"
                "    <method name=\"getFirmwareVersion\">\n"
                "      <arg direction=\"out\" type=\"s\"/>\n"
                "    </method>\n"
                "    <method name=\"getKeyboardLayout\">\n"
                "      <arg direction=\"out\" type=\"s\"/>\n"
                "    </method>\n"
                "    <method name=\"getDPI\">\n"
                "      <arg direction=\"out\" type=\"(qq)\"/>\n"
                "      <annotation value=\"RazerDPI\" name=\"org.qtproject.QtDBus.QtTypeName.Out0\"/>\n"
                "    </method>\n"
                "    <method name=\"setDPI\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"(qq)\" name=\"dpi\"/>\n"
                "      <annotation value=\"RazerDPI\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
                "    </method>\n"
                "    <method name=\"getPollRate\">\n"
                "      <arg direction=\"out\" type=\"q\"/>\n"
                "    </method>\n"
                "    <method name=\"setPollRate\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"q\" name=\"poll_rate\"/>\n"
                "    </method>\n"
                "    <method name=\"setNone\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"led\"/>\n"
                "      <annotation value=\"RazerLedId\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
                "    </method>\n"
                "    <method name=\"setStatic\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"led\"/>\n"
                "      <annotation value=\"RazerLedId\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"red\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"green\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"blue\"/>\n"
                "    </method>\n"
                "    <method name=\"setBreathing\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"led\"/>\n"
                "      <annotation value=\"RazerLedId\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"red\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"green\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"blue\"/>\n"
                "    </method>\n"
                "    <method name=\"setBreathingDual\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"led\"/>\n"
                "      <annotation value=\"RazerLedId\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"red\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"green\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"blue\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"red2\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"green2\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"blue2\"/>\n"
                "    </method>\n"
                "    <method name=\"setBreathingRandom\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"led\"/>\n"
                "      <annotation value=\"RazerLedId\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
                "    </method>\n"
                "    <method name=\"setBlinking\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"led\"/>\n"
                "      <annotation value=\"RazerLedId\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"red\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"green\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"blue\"/>\n"
                "    </method>\n"
                "    <method name=\"setSpectrum\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"led\"/>\n"
                "      <annotation value=\"RazerLedId\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
                "    </method>\n"
                "    <method name=\"setWave\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"led\"/>\n"
                "      <annotation value=\"RazerLedId\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"direction\"/>\n"
                "      <annotation value=\"WaveDirection\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
                "    </method>\n"
                "    <method name=\"setReactive\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"led\"/>\n"
                "      <annotation value=\"RazerLedId\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"speed\"/>\n"
                "      <annotation value=\"ReactiveSpeed\" name=\"org.qtproject.QtDBus.QtTypeName.In1\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"red\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"green\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"blue\"/>\n"
                "    </method>\n"
                "    <method name=\"displayCustomFrame\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "    </method>\n"
                "    <method name=\"defineCustomFrame\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"row\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"startColumn\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"endColumn\"/>\n"
                "      <arg direction=\"in\" type=\"ay\" name=\"rgbData\"/>\n"
                "    </method>\n"
                "    <method name=\"setBrightness\">\n"
                "      <arg direction=\"out\" type=\"b\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"led\"/>\n"
                "      <annotation value=\"RazerLedId\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
                "      <arg direction=\"in\" type=\"y\" name=\"brightness\"/>\n"
                "    </method>\n"
                "    <method name=\"getBrightness\">\n"
                "      <arg direction=\"out\" type=\"y\"/>\n"
                "      <arg direction=\"in\" type=\"(i)\" name=\"led\"/>\n"
                "      <annotation value=\"RazerLedId\" name=\"org.qtproject.QtDBus.QtTypeName.In0\"/>\n"
                "    </method>\n"
                "    <method name=\"startCustomEffectThread\"/>\n"
                "    <method name=\"pauseCustomEffectThread\"/>\n"
                "  </interface>\n"
                "")
public:
    RazerDeviceAdaptor(QObject *parent);
    virtual ~RazerDeviceAdaptor();

public: // PROPERTIES
    Q_PROPERTY(QVector<RazerLedId> LedIds READ ledIds)
    QVector<RazerLedId> ledIds() const;

    Q_PROPERTY(QString Name READ name)
    QString name() const;

    Q_PROPERTY(QStringList SupportedFeatures READ supportedFeatures)
    QStringList supportedFeatures() const;

    Q_PROPERTY(QStringList SupportedFx READ supportedFx)
    QStringList supportedFx() const;

    Q_PROPERTY(QString Type READ type)
    QString type() const;

public Q_SLOTS: // METHODS
    bool defineCustomFrame(uchar row, uchar startColumn, uchar endColumn, const QByteArray &rgbData);
    bool displayCustomFrame();
    uchar getBrightness(RazerLedId led);
    RazerDPI getDPI();
    QString getFirmwareVersion();
    QString getKeyboardLayout();
    ushort getPollRate();
    QString getSerial();
    void pauseCustomEffectThread();
    bool setBlinking(RazerLedId led, uchar red, uchar green, uchar blue);
    bool setBreathing(RazerLedId led, uchar red, uchar green, uchar blue);
    bool setBreathingDual(RazerLedId led, uchar red, uchar green, uchar blue, uchar red2, uchar green2, uchar blue2);
    bool setBreathingRandom(RazerLedId led);
    bool setBrightness(RazerLedId led, uchar brightness);
    bool setDPI(RazerDPI dpi);
    bool setNone(RazerLedId led);
    bool setPollRate(ushort poll_rate);
    bool setReactive(RazerLedId led, ReactiveSpeed speed, uchar red, uchar green, uchar blue);
    bool setSpectrum(RazerLedId led);
    bool setStatic(RazerLedId led, uchar red, uchar green, uchar blue);
    bool setWave(RazerLedId led, WaveDirection direction);
    void startCustomEffectThread();
Q_SIGNALS: // SIGNALS
};

#endif
