/*
 * This file was generated by qdbusxml2cpp version 0.8
 * Command line was: qdbusxml2cpp razerdevice.xml -a src/dbus/razerdeviceadaptor.h:src/dbus/razerdeviceadaptor.cpp
 *
 * qdbusxml2cpp is Copyright (C) 2017 The Qt Company Ltd.
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#include "src/dbus/razerdeviceadaptor.h"
#include <QtCore/QMetaObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>

/*
 * Implementation of adaptor class RazerDeviceAdaptor
 */

RazerDeviceAdaptor::RazerDeviceAdaptor(QObject *parent)
    : QDBusAbstractAdaptor(parent)
{
    // constructor
    setAutoRelaySignals(true);
}

RazerDeviceAdaptor::~RazerDeviceAdaptor()
{
    // destructor
}

QString RazerDeviceAdaptor::getFirmwareVersion()
{
    // handle method call local.RazerDevice.getFirmwareVersion
    QString out0;
    QMetaObject::invokeMethod(parent(), "getFirmwareVersion", Q_RETURN_ARG(QString, out0));
    return out0;
}

QString RazerDeviceAdaptor::getSerial()
{
    // handle method call local.RazerDevice.getSerial
    QString out0;
    QMetaObject::invokeMethod(parent(), "getSerial", Q_RETURN_ARG(QString, out0));
    return out0;
}

bool RazerDeviceAdaptor::initializeLeds()
{
    // handle method call local.RazerDevice.initializeLeds
    bool out0;
    QMetaObject::invokeMethod(parent(), "initializeLeds", Q_RETURN_ARG(bool, out0));
    return out0;
}

bool RazerDeviceAdaptor::setStatic(RazerLedId led, uchar red, uchar green, uchar blue)
{
    // handle method call local.RazerDevice.setStatic
    bool out0;
    QMetaObject::invokeMethod(parent(), "setStatic", Q_RETURN_ARG(bool, out0), Q_ARG(RazerLedId, led), Q_ARG(uchar, red), Q_ARG(uchar, green), Q_ARG(uchar, blue));
    return out0;
}

