name: macOS

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          python-version: '3.x'
      - run: brew install gcc
      - run: pip install meson ninja
      - name: Configure
        run: meson builddir
      - name: Build
        run: ninja -C builddir
