name: macOS

on: push

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: brew install qt@5 hidapi meson
      - run: echo "/usr/local/opt/qt@5/bin" >> $GITHUB_PATH
      - name: Configure
        run: meson builddir
      - name: Build
        run: ninja -C builddir
