name: macOS
on: [push, pull_request]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: brew install qt@6 hidapi meson
      - run: echo "/opt/homebrew/opt/qt@6/bin" >> $GITHUB_PATH
      - name: Configure
        run: meson setup builddir -Dbuild_bringup_util=true -Dbuild_tests=true
      - name: Build
        run: meson compile -C builddir
      - name: Test
        run: meson test -C builddir
