name: Ubuntu
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install qt6-base-dev libhidapi-dev libudev-dev meson
      - name: Configure
        run: meson setup builddir -Dbuild_bringup_util=true -Dbuild_tests=true
      - name: Build
        run: meson compile -C builddir
      - name: Test
        run: meson test -C builddir
