name: Ubuntu
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: sudo apt-get -y update
      - run: sudo apt-get -y install qt5-default libhidapi-dev libudev-dev meson
      - name: Configure
        run: meson -Dbuild_bringup_util=true -Dbuild_tests=true builddir/
      - name: Build
        run: ninja -C builddir/
      - name: Test
        run: ninja -C builddir/ test
